// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:67538406814:web:6765de1cdc8357c8d39a8f',
    messagingSenderId: '67538406814',
    projectId: 'evolvepro-f0620',
    authDomain: 'evolvepro-f0620.firebaseapp.com',
    storageBucket: 'evolvepro-f0620.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:67538406814:android:f5f1f5c9381f8e35d39a8f',
    messagingSenderId: '67538406814',
    projectId: 'evolvepro-f0620',
    storageBucket: 'evolvepro-f0620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:67538406814:ios:461c64bee3b6d6a6d39a8f',
    messagingSenderId: '67538406814',
    projectId: 'evolvepro-f0620',
    storageBucket: 'evolvepro-f0620.firebasestorage.app',
    iosBundleId: 'com.example.evolveproApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:67538406814:ios:461c64bee3b6d6a6d39a8f',
    messagingSenderId: '67538406814',
    projectId: 'evolvepro-f0620',
    storageBucket: 'evolvepro-f0620.firebasestorage.app',
    iosBundleId: 'com.example.evolveproApp',
  );
}
